# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_pois_enet <- function(x, y, alpha, lambda, intercept, maxit, tol) {
    .Call('poisens_fit_pois_enet', PACKAGE = 'poisens', x, y, alpha, lambda, intercept, maxit, tol)
}

fit_negbin_enet <- function(x, y, phi, alpha, lambda, intercept, maxit, tol) {
    .Call('poisens_fit_negbin_enet', PACKAGE = 'poisens', x, y, phi, alpha, lambda, intercept, maxit, tol)
}

phi_ml <- function(y, mu, maxit, tol) {
    .Call('poisens_phi_ml', PACKAGE = 'poisens', y, mu, maxit, tol)
}

fit_pois_reg <- function(x, y, maxit, tol) {
    .Call('poisens_fit_pois_reg', PACKAGE = 'poisens', x, y, maxit, tol)
}

fit_negbin_reg <- function(x, y, phi, maxit, tol) {
    .Call('poisens_fit_negbin_reg', PACKAGE = 'poisens', x, y, phi, maxit, tol)
}

